# Generated by Django 2.2.7 on 2020-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='deny',
        ),
        migrations.AddField(
            model_name='inscription',
            name='message',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('deny', 'deny')], default='pending', max_length=9),
        ),
    ]
