# Generated by Django 2.2.7 on 2020-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
