export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_ALL_FLASH_MESSAGE= 'DELETE_ALL_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_INSCRIPTIONS = 'SET_USER_INSCRIPTIONS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';